language: python
arch:
  - amd64
  - ppc64le
python:
  - "3.5"
before_install:
  - sudo chown -Rvf $USER:$GROUP ~/.cache/pip/wheels
install:
  - python setup.py install
  - pip install -r requirements-dev.txt

script:
  - cd tests
  - python run_tests.py
  - cd ..
  - flake8
